[package]
name = "rs_hpp_bridge"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
clang = { version = "2.0.0", features = ["clang_10_0"] }
clap = { version = "4.5.29", features = ["derive"] }
